### ISSUE TITLE
Cannot see /opt folder

### ISSUE THREAD

**Issue by selwynorren** [TenderOwl/Turtle#10]
Howdy,

Tried loading an app that I have in the /opt folder and its not able to see that folder at all. I presume this has to do with flatpak again.

**Comment by amka** [comment]
Hey! Probably it comes from the flatpak permissions. Turtle has permission to see files in the user's home folder, but not the root filesystem.
You can go to the system settings -> applications -> permissions and set access to the whole filesystem.

**Comment by selwynorren** [comment]
> Hey! Probably it comes from the flatpak permissions. Turtle has permission to see files in the user's home folder, but not the root filesystem.
> You can go to the system settings -> applications -> permissions and set access to the whole filesystem.

Oh wow, that worked perfectly!!! Thanks so much
