### ISSUE TITLE
If the source file isn't executable, it will "fail silently"

### ISSUE THREAD

**Issue by cshaa** [TenderOwl/Turtle#13]
Using Turtle to add an AppImage which isn't executable will create the `.desktop` file just fine, but it won't be visible in the App Menu. This is confusing to the user and makes Turtle look broken. I would prefer one of the following scenarios:

  * Turtle would refuse to create a `.desktop` entry for non-executable files, displaying an error.
  * Turtle would silently mark the file as executable, so that it would show in the App Menu (potential security issue!)
  * Turtle would tell the user that the chosen file is not executable, and ask them whether they want to make it executable or cancel the action.

The last variant sounds like the best UX to me.

**Comment by amka** [comment]
Hey, thank you for the suggestion. As for me, the last one looks more convenient too.

**Comment by amka** [comment]
@m93a kinda done :) It is in Russian, but I hope it's not a problem.
 
<video control src="https://user-images.githubusercontent.com/519146/131911386-bf328458-ef17-42b0-bdd5-0c8e95744b36.mp4" />

**Comment by cshaa** [comment]
Thanks for the quick solution, the implementation looks great! 😁
