### ISSUE TITLE
No way to remove added .desktop files

### ISSUE THREAD

**Issue by cassidyjames** [TenderOwl/Turtle#3]
It would probably be nice to users to offer a way to remove the generated files. At the very least, opening ~/.local/share/applications for manual editing, or better, listing those files in the app and letting the user modify/delete them.

**Comment by amka** [comment]
The origin idea of the Turtle is a fast action - put an application to the apps menu - such a Firefox or PyCharm, those apps available in the archive and have no option to add themselves to the menu. It wouldn't be that useful without an option to undo such action. 

That's a good idea to give users a screen with menu items and disable/remove buttons. But I don't want to make another AppEditor hope it will be available as Flatpak.

**Comment by amka** [comment]
Done in 0.2.0
